# Generated by Django 5.0 on 2023-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='capacity',
        ),
        migrations.AddField(
            model_name='container',
            name='capacity_length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='capacity_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='capacity_width',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(),
        ),
    ]
