# Generated by Django 5.0 on 2023-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='capacity_weight',
            field=models.FloatField(null=True),
        ),
    ]
